Replace stream with for loops in performance sensitive places
LaBoulangerie/LaBoulangerieMmo pull request #32
Opened 2024-12-23 11:25 UTC by GroobleDierne

2024-12-23 12:04 UTC, PainOchoco requested changes
Se référer au premier com pour les autres boucles, sinon ça me paraît bien. Ça améliore beaucoup les perfs ?

2024-12-23 12:04 UTC, PainOchoco commented on src/main/java/net/laboulangerie/laboulangeriemmo/core/blockus/BlockusListener.java
> +            if (LaBoulangerieMmo.PLUGIN.getBlockusHolder().getBlockus(event.getBlocks().get(i)) == null) continue;
L'indice ne sert pas, mieux vaut faire for (Block block : event.getBlocks())

2024-12-23 12:17 UTC, GroobleDierne commented
> Se référer au premier com pour les autres boucles, sinon ça me paraît bien. Ça améliore beaucoup les perfs ?

Pas beaucoup mais suffisamment pour que ça ait de l'importance quand c'est exécuté plusieurs fois chaque tick.
Et pour l'indice faudra que je fasse des recherches, je sais pas si ça change niveau performance d'utiliser l'indice ou - un itérateur

2024-12-23 12:20 UTC, PainOchoco commented
> > Se référer au premier com pour les autres boucles, sinon ça me paraît bien. Ça améliore beaucoup les perfs ?
> 
> Pas beaucoup mais suffisamment pour que ça ait de l'importance quand c'est exécuté plusieurs fois chaque tick.
> Et pour l'indice faudra que je fasse des recherches, je sais pas si ça change niveau performance d'utiliser l'indice ou - un itérateur

Ok, l'itérateur c'était plus pour la lisibilité du code

2024-12-23 15:08 UTC, GroobleDierne commented
![image](https://github.com/user-attachments/assets/0c478965-1626-4f60-9095-3639974f31fc)
Le forEach sur le graphe c'est la syntaxe `for (Block block : event.getBlocks())`

2024-12-23 15:59 UTC, PainOchoco commented
Source ? plus sérieusement les 2 devraient compiler le même code, t'es sûr que c'est pas le .forEach ?

2024-12-23 16:02 UTC, PainOchoco commented
https://stackoverflow.com/questions/256859/is-there-a-performance-difference-between-a-for-loop-and-a-for-each-loop

2024-12-23 18:40 UTC, GroobleDierne commented
https://medium.com/@greekykhs/for-loop-or-foreach-which-one-is-faster-in-java-bd46c951657b

2024-12-23 23:19 UTC, merged

2024-12-24 10:47 UTC, PainOchoco commented
L'article est pas bon y a un cast Integer ligne 18 c'est couteux, si tu fais le for sans le cast t'auras exactement le même code compilé, c'est une optimisation hyper simple du compilateur